//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS_BenhVien.HISReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TIEPNHANModel", Namespace="http://schemas.datacontract.org/2004/07/LinkHIS.Model")]
    [System.SerializableAttribute()]
    public partial class TIEPNHANModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BHYTDenNgayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BHYTTuNgayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BenhNhan_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaChiLienHeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaChiNguoiLienHeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DoiTuongCapTren_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DoiTuong_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HinhThucDenKham_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LyDoTiepNhan_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NgayTaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NgayTiepNhanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NguoiLienHeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NguoiLienHe_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NguoiTao_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NoiTiepNhan_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuanHuyen_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoBHYTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoThuTuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoTiepNhanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ThoiGianTiepNhanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ThuTienTruocField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TiepNhan_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TinhThanh_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TuyenKhamBenh_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int XaPhuong_IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BHYTDenNgay {
            get {
                return this.BHYTDenNgayField;
            }
            set {
                if ((this.BHYTDenNgayField.Equals(value) != true)) {
                    this.BHYTDenNgayField = value;
                    this.RaisePropertyChanged("BHYTDenNgay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BHYTTuNgay {
            get {
                return this.BHYTTuNgayField;
            }
            set {
                if ((this.BHYTTuNgayField.Equals(value) != true)) {
                    this.BHYTTuNgayField = value;
                    this.RaisePropertyChanged("BHYTTuNgay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BenhNhan_Id {
            get {
                return this.BenhNhan_IdField;
            }
            set {
                if ((this.BenhNhan_IdField.Equals(value) != true)) {
                    this.BenhNhan_IdField = value;
                    this.RaisePropertyChanged("BenhNhan_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiaChiLienHe {
            get {
                return this.DiaChiLienHeField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaChiLienHeField, value) != true)) {
                    this.DiaChiLienHeField = value;
                    this.RaisePropertyChanged("DiaChiLienHe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiaChiNguoiLienHe {
            get {
                return this.DiaChiNguoiLienHeField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaChiNguoiLienHeField, value) != true)) {
                    this.DiaChiNguoiLienHeField = value;
                    this.RaisePropertyChanged("DiaChiNguoiLienHe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DoiTuongCapTren_Id {
            get {
                return this.DoiTuongCapTren_IdField;
            }
            set {
                if ((this.DoiTuongCapTren_IdField.Equals(value) != true)) {
                    this.DoiTuongCapTren_IdField = value;
                    this.RaisePropertyChanged("DoiTuongCapTren_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DoiTuong_Id {
            get {
                return this.DoiTuong_IdField;
            }
            set {
                if ((this.DoiTuong_IdField.Equals(value) != true)) {
                    this.DoiTuong_IdField = value;
                    this.RaisePropertyChanged("DoiTuong_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HinhThucDenKham_Id {
            get {
                return this.HinhThucDenKham_IdField;
            }
            set {
                if ((this.HinhThucDenKham_IdField.Equals(value) != true)) {
                    this.HinhThucDenKham_IdField = value;
                    this.RaisePropertyChanged("HinhThucDenKham_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LyDoTiepNhan_Id {
            get {
                return this.LyDoTiepNhan_IdField;
            }
            set {
                if ((this.LyDoTiepNhan_IdField.Equals(value) != true)) {
                    this.LyDoTiepNhan_IdField = value;
                    this.RaisePropertyChanged("LyDoTiepNhan_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NgayTao {
            get {
                return this.NgayTaoField;
            }
            set {
                if ((this.NgayTaoField.Equals(value) != true)) {
                    this.NgayTaoField = value;
                    this.RaisePropertyChanged("NgayTao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NgayTiepNhan {
            get {
                return this.NgayTiepNhanField;
            }
            set {
                if ((this.NgayTiepNhanField.Equals(value) != true)) {
                    this.NgayTiepNhanField = value;
                    this.RaisePropertyChanged("NgayTiepNhan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NguoiLienHe {
            get {
                return this.NguoiLienHeField;
            }
            set {
                if ((object.ReferenceEquals(this.NguoiLienHeField, value) != true)) {
                    this.NguoiLienHeField = value;
                    this.RaisePropertyChanged("NguoiLienHe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NguoiLienHe_Id {
            get {
                return this.NguoiLienHe_IdField;
            }
            set {
                if ((this.NguoiLienHe_IdField.Equals(value) != true)) {
                    this.NguoiLienHe_IdField = value;
                    this.RaisePropertyChanged("NguoiLienHe_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NguoiTao_Id {
            get {
                return this.NguoiTao_IdField;
            }
            set {
                if ((this.NguoiTao_IdField.Equals(value) != true)) {
                    this.NguoiTao_IdField = value;
                    this.RaisePropertyChanged("NguoiTao_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NoiTiepNhan_Id {
            get {
                return this.NoiTiepNhan_IdField;
            }
            set {
                if ((this.NoiTiepNhan_IdField.Equals(value) != true)) {
                    this.NoiTiepNhan_IdField = value;
                    this.RaisePropertyChanged("NoiTiepNhan_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuanHuyen_Id {
            get {
                return this.QuanHuyen_IdField;
            }
            set {
                if ((this.QuanHuyen_IdField.Equals(value) != true)) {
                    this.QuanHuyen_IdField = value;
                    this.RaisePropertyChanged("QuanHuyen_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SoBHYT {
            get {
                return this.SoBHYTField;
            }
            set {
                if ((object.ReferenceEquals(this.SoBHYTField, value) != true)) {
                    this.SoBHYTField = value;
                    this.RaisePropertyChanged("SoBHYT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SoThuTu {
            get {
                return this.SoThuTuField;
            }
            set {
                if ((object.ReferenceEquals(this.SoThuTuField, value) != true)) {
                    this.SoThuTuField = value;
                    this.RaisePropertyChanged("SoThuTu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SoTiepNhan {
            get {
                return this.SoTiepNhanField;
            }
            set {
                if ((object.ReferenceEquals(this.SoTiepNhanField, value) != true)) {
                    this.SoTiepNhanField = value;
                    this.RaisePropertyChanged("SoTiepNhan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ThoiGianTiepNhan {
            get {
                return this.ThoiGianTiepNhanField;
            }
            set {
                if ((this.ThoiGianTiepNhanField.Equals(value) != true)) {
                    this.ThoiGianTiepNhanField = value;
                    this.RaisePropertyChanged("ThoiGianTiepNhan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ThuTienTruoc {
            get {
                return this.ThuTienTruocField;
            }
            set {
                if ((this.ThuTienTruocField.Equals(value) != true)) {
                    this.ThuTienTruocField = value;
                    this.RaisePropertyChanged("ThuTienTruoc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TiepNhan_Id {
            get {
                return this.TiepNhan_IdField;
            }
            set {
                if ((this.TiepNhan_IdField.Equals(value) != true)) {
                    this.TiepNhan_IdField = value;
                    this.RaisePropertyChanged("TiepNhan_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TinhThanh_Id {
            get {
                return this.TinhThanh_IdField;
            }
            set {
                if ((this.TinhThanh_IdField.Equals(value) != true)) {
                    this.TinhThanh_IdField = value;
                    this.RaisePropertyChanged("TinhThanh_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TuyenKhamBenh_Id {
            get {
                return this.TuyenKhamBenh_IdField;
            }
            set {
                if ((this.TuyenKhamBenh_IdField.Equals(value) != true)) {
                    this.TuyenKhamBenh_IdField = value;
                    this.RaisePropertyChanged("TuyenKhamBenh_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int XaPhuong_Id {
            get {
                return this.XaPhuong_IdField;
            }
            set {
                if ((this.XaPhuong_IdField.Equals(value) != true)) {
                    this.XaPhuong_IdField = value;
                    this.RaisePropertyChanged("XaPhuong_Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KQNhanLichSuKCBBS", Namespace="http://schemas.datacontract.org/2004/07/LinkHIS.Model")]
    [System.SerializableAttribute()]
    public partial class KQNhanLichSuKCBBS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cqBHXHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string diaChiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QMS_BenhVien.HISReference.LichSuKCB2018[] dsLichSuKCB2018Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QMS_BenhVien.HISReference.LichSuKT2018[] dsLichSuKT2018Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ghiChuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gioiTinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gtTheDenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gtTheDenMoiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gtTheTuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gtTheTuMoiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string hoTenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maDKBDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maKVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maKetQuaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maSoBHXHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maTheField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maTheCuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maTheMoiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ngayDu5NamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ngaySinhField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cqBHXH {
            get {
                return this.cqBHXHField;
            }
            set {
                if ((object.ReferenceEquals(this.cqBHXHField, value) != true)) {
                    this.cqBHXHField = value;
                    this.RaisePropertyChanged("cqBHXH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string diaChi {
            get {
                return this.diaChiField;
            }
            set {
                if ((object.ReferenceEquals(this.diaChiField, value) != true)) {
                    this.diaChiField = value;
                    this.RaisePropertyChanged("diaChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QMS_BenhVien.HISReference.LichSuKCB2018[] dsLichSuKCB2018 {
            get {
                return this.dsLichSuKCB2018Field;
            }
            set {
                if ((object.ReferenceEquals(this.dsLichSuKCB2018Field, value) != true)) {
                    this.dsLichSuKCB2018Field = value;
                    this.RaisePropertyChanged("dsLichSuKCB2018");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QMS_BenhVien.HISReference.LichSuKT2018[] dsLichSuKT2018 {
            get {
                return this.dsLichSuKT2018Field;
            }
            set {
                if ((object.ReferenceEquals(this.dsLichSuKT2018Field, value) != true)) {
                    this.dsLichSuKT2018Field = value;
                    this.RaisePropertyChanged("dsLichSuKT2018");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ghiChu {
            get {
                return this.ghiChuField;
            }
            set {
                if ((object.ReferenceEquals(this.ghiChuField, value) != true)) {
                    this.ghiChuField = value;
                    this.RaisePropertyChanged("ghiChu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gioiTinh {
            get {
                return this.gioiTinhField;
            }
            set {
                if ((object.ReferenceEquals(this.gioiTinhField, value) != true)) {
                    this.gioiTinhField = value;
                    this.RaisePropertyChanged("gioiTinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gtTheDen {
            get {
                return this.gtTheDenField;
            }
            set {
                if ((object.ReferenceEquals(this.gtTheDenField, value) != true)) {
                    this.gtTheDenField = value;
                    this.RaisePropertyChanged("gtTheDen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gtTheDenMoi {
            get {
                return this.gtTheDenMoiField;
            }
            set {
                if ((object.ReferenceEquals(this.gtTheDenMoiField, value) != true)) {
                    this.gtTheDenMoiField = value;
                    this.RaisePropertyChanged("gtTheDenMoi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gtTheTu {
            get {
                return this.gtTheTuField;
            }
            set {
                if ((object.ReferenceEquals(this.gtTheTuField, value) != true)) {
                    this.gtTheTuField = value;
                    this.RaisePropertyChanged("gtTheTu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gtTheTuMoi {
            get {
                return this.gtTheTuMoiField;
            }
            set {
                if ((object.ReferenceEquals(this.gtTheTuMoiField, value) != true)) {
                    this.gtTheTuMoiField = value;
                    this.RaisePropertyChanged("gtTheTuMoi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string hoTen {
            get {
                return this.hoTenField;
            }
            set {
                if ((object.ReferenceEquals(this.hoTenField, value) != true)) {
                    this.hoTenField = value;
                    this.RaisePropertyChanged("hoTen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maDKBD {
            get {
                return this.maDKBDField;
            }
            set {
                if ((object.ReferenceEquals(this.maDKBDField, value) != true)) {
                    this.maDKBDField = value;
                    this.RaisePropertyChanged("maDKBD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maKV {
            get {
                return this.maKVField;
            }
            set {
                if ((object.ReferenceEquals(this.maKVField, value) != true)) {
                    this.maKVField = value;
                    this.RaisePropertyChanged("maKV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maKetQua {
            get {
                return this.maKetQuaField;
            }
            set {
                if ((object.ReferenceEquals(this.maKetQuaField, value) != true)) {
                    this.maKetQuaField = value;
                    this.RaisePropertyChanged("maKetQua");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maSoBHXH {
            get {
                return this.maSoBHXHField;
            }
            set {
                if ((object.ReferenceEquals(this.maSoBHXHField, value) != true)) {
                    this.maSoBHXHField = value;
                    this.RaisePropertyChanged("maSoBHXH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maThe {
            get {
                return this.maTheField;
            }
            set {
                if ((object.ReferenceEquals(this.maTheField, value) != true)) {
                    this.maTheField = value;
                    this.RaisePropertyChanged("maThe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maTheCu {
            get {
                return this.maTheCuField;
            }
            set {
                if ((object.ReferenceEquals(this.maTheCuField, value) != true)) {
                    this.maTheCuField = value;
                    this.RaisePropertyChanged("maTheCu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maTheMoi {
            get {
                return this.maTheMoiField;
            }
            set {
                if ((object.ReferenceEquals(this.maTheMoiField, value) != true)) {
                    this.maTheMoiField = value;
                    this.RaisePropertyChanged("maTheMoi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ngayDu5Nam {
            get {
                return this.ngayDu5NamField;
            }
            set {
                if ((object.ReferenceEquals(this.ngayDu5NamField, value) != true)) {
                    this.ngayDu5NamField = value;
                    this.RaisePropertyChanged("ngayDu5Nam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ngaySinh {
            get {
                return this.ngaySinhField;
            }
            set {
                if ((object.ReferenceEquals(this.ngaySinhField, value) != true)) {
                    this.ngaySinhField = value;
                    this.RaisePropertyChanged("ngaySinh");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LichSuKCB2018", Namespace="http://schemas.datacontract.org/2004/07/LinkHIS.Model")]
    [System.SerializableAttribute()]
    public partial class LichSuKCB2018 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kqDieuTriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maCSKCBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maHoSoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ngayRaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ngayVaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tenBenhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tinhTrangField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string kqDieuTri {
            get {
                return this.kqDieuTriField;
            }
            set {
                if ((object.ReferenceEquals(this.kqDieuTriField, value) != true)) {
                    this.kqDieuTriField = value;
                    this.RaisePropertyChanged("kqDieuTri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maCSKCB {
            get {
                return this.maCSKCBField;
            }
            set {
                if ((object.ReferenceEquals(this.maCSKCBField, value) != true)) {
                    this.maCSKCBField = value;
                    this.RaisePropertyChanged("maCSKCB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maHoSo {
            get {
                return this.maHoSoField;
            }
            set {
                if ((object.ReferenceEquals(this.maHoSoField, value) != true)) {
                    this.maHoSoField = value;
                    this.RaisePropertyChanged("maHoSo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ngayRa {
            get {
                return this.ngayRaField;
            }
            set {
                if ((object.ReferenceEquals(this.ngayRaField, value) != true)) {
                    this.ngayRaField = value;
                    this.RaisePropertyChanged("ngayRa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ngayVao {
            get {
                return this.ngayVaoField;
            }
            set {
                if ((object.ReferenceEquals(this.ngayVaoField, value) != true)) {
                    this.ngayVaoField = value;
                    this.RaisePropertyChanged("ngayVao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tenBenh {
            get {
                return this.tenBenhField;
            }
            set {
                if ((object.ReferenceEquals(this.tenBenhField, value) != true)) {
                    this.tenBenhField = value;
                    this.RaisePropertyChanged("tenBenh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tinhTrang {
            get {
                return this.tinhTrangField;
            }
            set {
                if ((object.ReferenceEquals(this.tinhTrangField, value) != true)) {
                    this.tinhTrangField = value;
                    this.RaisePropertyChanged("tinhTrang");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LichSuKT2018", Namespace="http://schemas.datacontract.org/2004/07/LinkHIS.Model")]
    [System.SerializableAttribute()]
    public partial class LichSuKT2018 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maLoiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string thoiGianKTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string thongBaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userKTField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maLoi {
            get {
                return this.maLoiField;
            }
            set {
                if ((object.ReferenceEquals(this.maLoiField, value) != true)) {
                    this.maLoiField = value;
                    this.RaisePropertyChanged("maLoi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string thoiGianKT {
            get {
                return this.thoiGianKTField;
            }
            set {
                if ((object.ReferenceEquals(this.thoiGianKTField, value) != true)) {
                    this.thoiGianKTField = value;
                    this.RaisePropertyChanged("thoiGianKT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string thongBao {
            get {
                return this.thongBaoField;
            }
            set {
                if ((object.ReferenceEquals(this.thongBaoField, value) != true)) {
                    this.thongBaoField = value;
                    this.RaisePropertyChanged("thongBao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userKT {
            get {
                return this.userKTField;
            }
            set {
                if ((object.ReferenceEquals(this.userKTField, value) != true)) {
                    this.userKTField = value;
                    this.RaisePropertyChanged("userKT");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DM_BENHNHANModel", Namespace="http://schemas.datacontract.org/2004/07/LinkHIS.Model")]
    [System.SerializableAttribute()]
    public partial class DM_BENHNHANModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BHYTDenNgayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BHYTTuNgayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BenhNhan_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CMNDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DanToc_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaChiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GioiTinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaYTeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NamSinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NgaySinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool NguoiNuocNgoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> QuanHuyen_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> QuocTich_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoBHYTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoVaoVienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenBenhNhanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenKhongDauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TinhThanh_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> XaPhuong_IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BHYTDenNgay {
            get {
                return this.BHYTDenNgayField;
            }
            set {
                if ((object.ReferenceEquals(this.BHYTDenNgayField, value) != true)) {
                    this.BHYTDenNgayField = value;
                    this.RaisePropertyChanged("BHYTDenNgay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BHYTTuNgay {
            get {
                return this.BHYTTuNgayField;
            }
            set {
                if ((object.ReferenceEquals(this.BHYTTuNgayField, value) != true)) {
                    this.BHYTTuNgayField = value;
                    this.RaisePropertyChanged("BHYTTuNgay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BenhNhan_Id {
            get {
                return this.BenhNhan_IdField;
            }
            set {
                if ((this.BenhNhan_IdField.Equals(value) != true)) {
                    this.BenhNhan_IdField = value;
                    this.RaisePropertyChanged("BenhNhan_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CMND {
            get {
                return this.CMNDField;
            }
            set {
                if ((object.ReferenceEquals(this.CMNDField, value) != true)) {
                    this.CMNDField = value;
                    this.RaisePropertyChanged("CMND");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DanToc_Id {
            get {
                return this.DanToc_IdField;
            }
            set {
                if ((this.DanToc_IdField.Equals(value) != true)) {
                    this.DanToc_IdField = value;
                    this.RaisePropertyChanged("DanToc_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiaChi {
            get {
                return this.DiaChiField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaChiField, value) != true)) {
                    this.DiaChiField = value;
                    this.RaisePropertyChanged("DiaChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GioiTinh {
            get {
                return this.GioiTinhField;
            }
            set {
                if ((object.ReferenceEquals(this.GioiTinhField, value) != true)) {
                    this.GioiTinhField = value;
                    this.RaisePropertyChanged("GioiTinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaYTe {
            get {
                return this.MaYTeField;
            }
            set {
                if ((object.ReferenceEquals(this.MaYTeField, value) != true)) {
                    this.MaYTeField = value;
                    this.RaisePropertyChanged("MaYTe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NamSinh {
            get {
                return this.NamSinhField;
            }
            set {
                if ((this.NamSinhField.Equals(value) != true)) {
                    this.NamSinhField = value;
                    this.RaisePropertyChanged("NamSinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NgaySinh {
            get {
                return this.NgaySinhField;
            }
            set {
                if ((this.NgaySinhField.Equals(value) != true)) {
                    this.NgaySinhField = value;
                    this.RaisePropertyChanged("NgaySinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NguoiNuocNgoai {
            get {
                return this.NguoiNuocNgoaiField;
            }
            set {
                if ((this.NguoiNuocNgoaiField.Equals(value) != true)) {
                    this.NguoiNuocNgoaiField = value;
                    this.RaisePropertyChanged("NguoiNuocNgoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> QuanHuyen_Id {
            get {
                return this.QuanHuyen_IdField;
            }
            set {
                if ((this.QuanHuyen_IdField.Equals(value) != true)) {
                    this.QuanHuyen_IdField = value;
                    this.RaisePropertyChanged("QuanHuyen_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> QuocTich_Id {
            get {
                return this.QuocTich_IdField;
            }
            set {
                if ((this.QuocTich_IdField.Equals(value) != true)) {
                    this.QuocTich_IdField = value;
                    this.RaisePropertyChanged("QuocTich_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SoBHYT {
            get {
                return this.SoBHYTField;
            }
            set {
                if ((object.ReferenceEquals(this.SoBHYTField, value) != true)) {
                    this.SoBHYTField = value;
                    this.RaisePropertyChanged("SoBHYT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SoVaoVien {
            get {
                return this.SoVaoVienField;
            }
            set {
                if ((object.ReferenceEquals(this.SoVaoVienField, value) != true)) {
                    this.SoVaoVienField = value;
                    this.RaisePropertyChanged("SoVaoVien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenBenhNhan {
            get {
                return this.TenBenhNhanField;
            }
            set {
                if ((object.ReferenceEquals(this.TenBenhNhanField, value) != true)) {
                    this.TenBenhNhanField = value;
                    this.RaisePropertyChanged("TenBenhNhan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenKhongDau {
            get {
                return this.TenKhongDauField;
            }
            set {
                if ((object.ReferenceEquals(this.TenKhongDauField, value) != true)) {
                    this.TenKhongDauField = value;
                    this.RaisePropertyChanged("TenKhongDau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TinhThanh_Id {
            get {
                return this.TinhThanh_IdField;
            }
            set {
                if ((this.TinhThanh_IdField.Equals(value) != true)) {
                    this.TinhThanh_IdField = value;
                    this.RaisePropertyChanged("TinhThanh_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> XaPhuong_Id {
            get {
                return this.XaPhuong_IdField;
            }
            set {
                if ((this.XaPhuong_IdField.Equals(value) != true)) {
                    this.XaPhuong_IdField = value;
                    this.RaisePropertyChanged("XaPhuong_Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HISReference.IHISService")]
    public interface IHISService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHISService/Check_KhamBenhLanDau", ReplyAction="http://tempuri.org/IHISService/Check_KhamBenhLanDauResponse")]
        QMS_BenhVien.HISReference.Check_KhamBenhLanDauResponse Check_KhamBenhLanDau(QMS_BenhVien.HISReference.Check_KhamBenhLanDauRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHISService/Check_KhamBenhLanDau", ReplyAction="http://tempuri.org/IHISService/Check_KhamBenhLanDauResponse")]
        System.Threading.Tasks.Task<QMS_BenhVien.HISReference.Check_KhamBenhLanDauResponse> Check_KhamBenhLanDauAsync(QMS_BenhVien.HISReference.Check_KhamBenhLanDauRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHISService/DongBoDanhMuc", ReplyAction="http://tempuri.org/IHISService/DongBoDanhMucResponse")]
        string DongBoDanhMuc(string pMaDanhMuc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHISService/DongBoDanhMuc", ReplyAction="http://tempuri.org/IHISService/DongBoDanhMucResponse")]
        System.Threading.Tasks.Task<string> DongBoDanhMucAsync(string pMaDanhMuc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHISService/GetAllChiDinhCLS", ReplyAction="http://tempuri.org/IHISService/GetAllChiDinhCLSResponse")]
        System.Data.DataSet GetAllChiDinhCLS(string pMaBenhNhan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHISService/GetAllChiDinhCLS", ReplyAction="http://tempuri.org/IHISService/GetAllChiDinhCLSResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllChiDinhCLSAsync(string pMaBenhNhan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHISService/LayThongTinKhamTrongNgay", ReplyAction="http://tempuri.org/IHISService/LayThongTinKhamTrongNgayResponse")]
        System.Data.DataSet LayThongTinKhamTrongNgay(string pMaBenhNhan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHISService/LayThongTinKhamTrongNgay", ReplyAction="http://tempuri.org/IHISService/LayThongTinKhamTrongNgayResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> LayThongTinKhamTrongNgayAsync(string pMaBenhNhan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHISService/GetThongTinTiepNhan_TrongNgay", ReplyAction="http://tempuri.org/IHISService/GetThongTinTiepNhan_TrongNgayResponse")]
        QMS_BenhVien.HISReference.TIEPNHANModel GetThongTinTiepNhan_TrongNgay(string pMaBenhNhan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHISService/GetThongTinTiepNhan_TrongNgay", ReplyAction="http://tempuri.org/IHISService/GetThongTinTiepNhan_TrongNgayResponse")]
        System.Threading.Tasks.Task<QMS_BenhVien.HISReference.TIEPNHANModel> GetThongTinTiepNhan_TrongNgayAsync(string pMaBenhNhan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHISService/NhanLichSuKCB", ReplyAction="http://tempuri.org/IHISService/NhanLichSuKCBResponse")]
        QMS_BenhVien.HISReference.NhanLichSuKCBResponse NhanLichSuKCB(QMS_BenhVien.HISReference.NhanLichSuKCBRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHISService/NhanLichSuKCB", ReplyAction="http://tempuri.org/IHISService/NhanLichSuKCBResponse")]
        System.Threading.Tasks.Task<QMS_BenhVien.HISReference.NhanLichSuKCBResponse> NhanLichSuKCBAsync(QMS_BenhVien.HISReference.NhanLichSuKCBRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHISService/GetBenhNhanInfo_ByMaBenhNhan", ReplyAction="http://tempuri.org/IHISService/GetBenhNhanInfo_ByMaBenhNhanResponse")]
        QMS_BenhVien.HISReference.DM_BENHNHANModel GetBenhNhanInfo_ByMaBenhNhan(string pMaBenhNhan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHISService/GetBenhNhanInfo_ByMaBenhNhan", ReplyAction="http://tempuri.org/IHISService/GetBenhNhanInfo_ByMaBenhNhanResponse")]
        System.Threading.Tasks.Task<QMS_BenhVien.HISReference.DM_BENHNHANModel> GetBenhNhanInfo_ByMaBenhNhanAsync(string pMaBenhNhan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHISService/Check_ChuaRaVien_ByMaBenhNhan", ReplyAction="http://tempuri.org/IHISService/Check_ChuaRaVien_ByMaBenhNhanResponse")]
        string Check_ChuaRaVien_ByMaBenhNhan(string pMaBenhNhan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHISService/Check_ChuaRaVien_ByMaBenhNhan", ReplyAction="http://tempuri.org/IHISService/Check_ChuaRaVien_ByMaBenhNhanResponse")]
        System.Threading.Tasks.Task<string> Check_ChuaRaVien_ByMaBenhNhanAsync(string pMaBenhNhan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHISService/Luu_TiepNhan", ReplyAction="http://tempuri.org/IHISService/Luu_TiepNhanResponse")]
        bool Luu_TiepNhan(string pMaBenhNhan, System.DateTime pNgaySinh, string pGioiTinh, string pSoTheBHYT, System.DateTime pNgayHieuLuc, System.DateTime pNgayHetHieuLuc, int pDichVu_Id, int pPhongKham_Id, int pBacSiChiDinh_Id, string pSoThuTu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHISService/Luu_TiepNhan", ReplyAction="http://tempuri.org/IHISService/Luu_TiepNhanResponse")]
        System.Threading.Tasks.Task<bool> Luu_TiepNhanAsync(string pMaBenhNhan, System.DateTime pNgaySinh, string pGioiTinh, string pSoTheBHYT, System.DateTime pNgayHieuLuc, System.DateTime pNgayHetHieuLuc, int pDichVu_Id, int pPhongKham_Id, int pBacSiChiDinh_Id, string pSoThuTu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHISService/GetDanhMucKhoa_PK_DichVu", ReplyAction="http://tempuri.org/IHISService/GetDanhMucKhoa_PK_DichVuResponse")]
        string GetDanhMucKhoa_PK_DichVu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHISService/GetDanhMucKhoa_PK_DichVu", ReplyAction="http://tempuri.org/IHISService/GetDanhMucKhoa_PK_DichVuResponse")]
        System.Threading.Tasks.Task<string> GetDanhMucKhoa_PK_DichVuAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHISService/GetDanhMucKhoa_PK_DichVu_CLS", ReplyAction="http://tempuri.org/IHISService/GetDanhMucKhoa_PK_DichVu_CLSResponse")]
        string GetDanhMucKhoa_PK_DichVu_CLS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHISService/GetDanhMucKhoa_PK_DichVu_CLS", ReplyAction="http://tempuri.org/IHISService/GetDanhMucKhoa_PK_DichVu_CLSResponse")]
        System.Threading.Tasks.Task<string> GetDanhMucKhoa_PK_DichVu_CLSAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHISService/SendSoThuTuToHIS", ReplyAction="http://tempuri.org/IHISService/SendSoThuTuToHISResponse")]
        bool SendSoThuTuToHIS(string pMaBenhNhan, string pLoaiCLS, string pSoThuTu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHISService/SendSoThuTuToHIS", ReplyAction="http://tempuri.org/IHISService/SendSoThuTuToHISResponse")]
        System.Threading.Tasks.Task<bool> SendSoThuTuToHISAsync(string pMaBenhNhan, string pLoaiCLS, string pSoThuTu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHISService/LayDanhSachDatHenTrongNgay", ReplyAction="http://tempuri.org/IHISService/LayDanhSachDatHenTrongNgayResponse")]
        string LayDanhSachDatHenTrongNgay();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHISService/LayDanhSachDatHenTrongNgay", ReplyAction="http://tempuri.org/IHISService/LayDanhSachDatHenTrongNgayResponse")]
        System.Threading.Tasks.Task<string> LayDanhSachDatHenTrongNgayAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHISService/LayThongTinDatHen_ByMaBenhNhan", ReplyAction="http://tempuri.org/IHISService/LayThongTinDatHen_ByMaBenhNhanResponse")]
        string LayThongTinDatHen_ByMaBenhNhan(string pMaBenhNhan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHISService/LayThongTinDatHen_ByMaBenhNhan", ReplyAction="http://tempuri.org/IHISService/LayThongTinDatHen_ByMaBenhNhanResponse")]
        System.Threading.Tasks.Task<string> LayThongTinDatHen_ByMaBenhNhanAsync(string pMaBenhNhan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHISService/Valid_TiepNhan", ReplyAction="http://tempuri.org/IHISService/Valid_TiepNhanResponse")]
        QMS_BenhVien.HISReference.Valid_TiepNhanResponse Valid_TiepNhan(QMS_BenhVien.HISReference.Valid_TiepNhanRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHISService/Valid_TiepNhan", ReplyAction="http://tempuri.org/IHISService/Valid_TiepNhanResponse")]
        System.Threading.Tasks.Task<QMS_BenhVien.HISReference.Valid_TiepNhanResponse> Valid_TiepNhanAsync(QMS_BenhVien.HISReference.Valid_TiepNhanRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Check_KhamBenhLanDau", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Check_KhamBenhLanDauRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string pSoBHYT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pTenBenhNhan;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int pNamSinh;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string pGioiTinh;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string pMaBenhNhan;
        
        public Check_KhamBenhLanDauRequest() {
        }
        
        public Check_KhamBenhLanDauRequest(string pSoBHYT, string pTenBenhNhan, int pNamSinh, string pGioiTinh, string pMaBenhNhan) {
            this.pSoBHYT = pSoBHYT;
            this.pTenBenhNhan = pTenBenhNhan;
            this.pNamSinh = pNamSinh;
            this.pGioiTinh = pGioiTinh;
            this.pMaBenhNhan = pMaBenhNhan;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Check_KhamBenhLanDauResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Check_KhamBenhLanDauResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Check_KhamBenhLanDauResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pMaBenhNhan;
        
        public Check_KhamBenhLanDauResponse() {
        }
        
        public Check_KhamBenhLanDauResponse(bool Check_KhamBenhLanDauResult, string pMaBenhNhan) {
            this.Check_KhamBenhLanDauResult = Check_KhamBenhLanDauResult;
            this.pMaBenhNhan = pMaBenhNhan;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NhanLichSuKCB", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class NhanLichSuKCBRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string soThe;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string hoten;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string ngaysinh;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string msg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string maKQ;
        
        public NhanLichSuKCBRequest() {
        }
        
        public NhanLichSuKCBRequest(string soThe, string hoten, string ngaysinh, string msg, string maKQ) {
            this.soThe = soThe;
            this.hoten = hoten;
            this.ngaysinh = ngaysinh;
            this.msg = msg;
            this.maKQ = maKQ;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NhanLichSuKCBResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class NhanLichSuKCBResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public QMS_BenhVien.HISReference.KQNhanLichSuKCBBS NhanLichSuKCBResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string msg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string maKQ;
        
        public NhanLichSuKCBResponse() {
        }
        
        public NhanLichSuKCBResponse(QMS_BenhVien.HISReference.KQNhanLichSuKCBBS NhanLichSuKCBResult, string msg, string maKQ) {
            this.NhanLichSuKCBResult = NhanLichSuKCBResult;
            this.msg = msg;
            this.maKQ = maKQ;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Valid_TiepNhan", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Valid_TiepNhanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string pMaBenhNhan;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pMessage;
        
        public Valid_TiepNhanRequest() {
        }
        
        public Valid_TiepNhanRequest(string pMaBenhNhan, string pMessage) {
            this.pMaBenhNhan = pMaBenhNhan;
            this.pMessage = pMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Valid_TiepNhanResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Valid_TiepNhanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Valid_TiepNhanResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pMessage;
        
        public Valid_TiepNhanResponse() {
        }
        
        public Valid_TiepNhanResponse(bool Valid_TiepNhanResult, string pMessage) {
            this.Valid_TiepNhanResult = Valid_TiepNhanResult;
            this.pMessage = pMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHISServiceChannel : QMS_BenhVien.HISReference.IHISService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HISServiceClient : System.ServiceModel.ClientBase<QMS_BenhVien.HISReference.IHISService>, QMS_BenhVien.HISReference.IHISService {
        
        public HISServiceClient() {
        }
        
        public HISServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HISServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HISServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HISServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QMS_BenhVien.HISReference.Check_KhamBenhLanDauResponse QMS_BenhVien.HISReference.IHISService.Check_KhamBenhLanDau(QMS_BenhVien.HISReference.Check_KhamBenhLanDauRequest request) {
            return base.Channel.Check_KhamBenhLanDau(request);
        }
        
        public bool Check_KhamBenhLanDau(string pSoBHYT, string pTenBenhNhan, int pNamSinh, string pGioiTinh, ref string pMaBenhNhan) {
            QMS_BenhVien.HISReference.Check_KhamBenhLanDauRequest inValue = new QMS_BenhVien.HISReference.Check_KhamBenhLanDauRequest();
            inValue.pSoBHYT = pSoBHYT;
            inValue.pTenBenhNhan = pTenBenhNhan;
            inValue.pNamSinh = pNamSinh;
            inValue.pGioiTinh = pGioiTinh;
            inValue.pMaBenhNhan = pMaBenhNhan;
            QMS_BenhVien.HISReference.Check_KhamBenhLanDauResponse retVal = ((QMS_BenhVien.HISReference.IHISService)(this)).Check_KhamBenhLanDau(inValue);
            pMaBenhNhan = retVal.pMaBenhNhan;
            return retVal.Check_KhamBenhLanDauResult;
        }
        
        public System.Threading.Tasks.Task<QMS_BenhVien.HISReference.Check_KhamBenhLanDauResponse> Check_KhamBenhLanDauAsync(QMS_BenhVien.HISReference.Check_KhamBenhLanDauRequest request) {
            return base.Channel.Check_KhamBenhLanDauAsync(request);
        }
        
        public string DongBoDanhMuc(string pMaDanhMuc) {
            return base.Channel.DongBoDanhMuc(pMaDanhMuc);
        }
        
        public System.Threading.Tasks.Task<string> DongBoDanhMucAsync(string pMaDanhMuc) {
            return base.Channel.DongBoDanhMucAsync(pMaDanhMuc);
        }
        
        public System.Data.DataSet GetAllChiDinhCLS(string pMaBenhNhan) {
            return base.Channel.GetAllChiDinhCLS(pMaBenhNhan);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllChiDinhCLSAsync(string pMaBenhNhan) {
            return base.Channel.GetAllChiDinhCLSAsync(pMaBenhNhan);
        }
        
        public System.Data.DataSet LayThongTinKhamTrongNgay(string pMaBenhNhan) {
            return base.Channel.LayThongTinKhamTrongNgay(pMaBenhNhan);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> LayThongTinKhamTrongNgayAsync(string pMaBenhNhan) {
            return base.Channel.LayThongTinKhamTrongNgayAsync(pMaBenhNhan);
        }
        
        public QMS_BenhVien.HISReference.TIEPNHANModel GetThongTinTiepNhan_TrongNgay(string pMaBenhNhan) {
            return base.Channel.GetThongTinTiepNhan_TrongNgay(pMaBenhNhan);
        }
        
        public System.Threading.Tasks.Task<QMS_BenhVien.HISReference.TIEPNHANModel> GetThongTinTiepNhan_TrongNgayAsync(string pMaBenhNhan) {
            return base.Channel.GetThongTinTiepNhan_TrongNgayAsync(pMaBenhNhan);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QMS_BenhVien.HISReference.NhanLichSuKCBResponse QMS_BenhVien.HISReference.IHISService.NhanLichSuKCB(QMS_BenhVien.HISReference.NhanLichSuKCBRequest request) {
            return base.Channel.NhanLichSuKCB(request);
        }
        
        public QMS_BenhVien.HISReference.KQNhanLichSuKCBBS NhanLichSuKCB(string soThe, string hoten, string ngaysinh, ref string msg, ref string maKQ) {
            QMS_BenhVien.HISReference.NhanLichSuKCBRequest inValue = new QMS_BenhVien.HISReference.NhanLichSuKCBRequest();
            inValue.soThe = soThe;
            inValue.hoten = hoten;
            inValue.ngaysinh = ngaysinh;
            inValue.msg = msg;
            inValue.maKQ = maKQ;
            QMS_BenhVien.HISReference.NhanLichSuKCBResponse retVal = ((QMS_BenhVien.HISReference.IHISService)(this)).NhanLichSuKCB(inValue);
            msg = retVal.msg;
            maKQ = retVal.maKQ;
            return retVal.NhanLichSuKCBResult;
        }
        
        public System.Threading.Tasks.Task<QMS_BenhVien.HISReference.NhanLichSuKCBResponse> NhanLichSuKCBAsync(QMS_BenhVien.HISReference.NhanLichSuKCBRequest request) {
            return base.Channel.NhanLichSuKCBAsync(request);
        }
        
        public QMS_BenhVien.HISReference.DM_BENHNHANModel GetBenhNhanInfo_ByMaBenhNhan(string pMaBenhNhan) {
            return base.Channel.GetBenhNhanInfo_ByMaBenhNhan(pMaBenhNhan);
        }
        
        public System.Threading.Tasks.Task<QMS_BenhVien.HISReference.DM_BENHNHANModel> GetBenhNhanInfo_ByMaBenhNhanAsync(string pMaBenhNhan) {
            return base.Channel.GetBenhNhanInfo_ByMaBenhNhanAsync(pMaBenhNhan);
        }
        
        public string Check_ChuaRaVien_ByMaBenhNhan(string pMaBenhNhan) {
            return base.Channel.Check_ChuaRaVien_ByMaBenhNhan(pMaBenhNhan);
        }
        
        public System.Threading.Tasks.Task<string> Check_ChuaRaVien_ByMaBenhNhanAsync(string pMaBenhNhan) {
            return base.Channel.Check_ChuaRaVien_ByMaBenhNhanAsync(pMaBenhNhan);
        }
        
        public bool Luu_TiepNhan(string pMaBenhNhan, System.DateTime pNgaySinh, string pGioiTinh, string pSoTheBHYT, System.DateTime pNgayHieuLuc, System.DateTime pNgayHetHieuLuc, int pDichVu_Id, int pPhongKham_Id, int pBacSiChiDinh_Id, string pSoThuTu) {
            return base.Channel.Luu_TiepNhan(pMaBenhNhan, pNgaySinh, pGioiTinh, pSoTheBHYT, pNgayHieuLuc, pNgayHetHieuLuc, pDichVu_Id, pPhongKham_Id, pBacSiChiDinh_Id, pSoThuTu);
        }
        
        public System.Threading.Tasks.Task<bool> Luu_TiepNhanAsync(string pMaBenhNhan, System.DateTime pNgaySinh, string pGioiTinh, string pSoTheBHYT, System.DateTime pNgayHieuLuc, System.DateTime pNgayHetHieuLuc, int pDichVu_Id, int pPhongKham_Id, int pBacSiChiDinh_Id, string pSoThuTu) {
            return base.Channel.Luu_TiepNhanAsync(pMaBenhNhan, pNgaySinh, pGioiTinh, pSoTheBHYT, pNgayHieuLuc, pNgayHetHieuLuc, pDichVu_Id, pPhongKham_Id, pBacSiChiDinh_Id, pSoThuTu);
        }
        
        public string GetDanhMucKhoa_PK_DichVu() {
            return base.Channel.GetDanhMucKhoa_PK_DichVu();
        }
        
        public System.Threading.Tasks.Task<string> GetDanhMucKhoa_PK_DichVuAsync() {
            return base.Channel.GetDanhMucKhoa_PK_DichVuAsync();
        }
        
        public string GetDanhMucKhoa_PK_DichVu_CLS() {
            return base.Channel.GetDanhMucKhoa_PK_DichVu_CLS();
        }
        
        public System.Threading.Tasks.Task<string> GetDanhMucKhoa_PK_DichVu_CLSAsync() {
            return base.Channel.GetDanhMucKhoa_PK_DichVu_CLSAsync();
        }
        
        public bool SendSoThuTuToHIS(string pMaBenhNhan, string pLoaiCLS, string pSoThuTu) {
            return base.Channel.SendSoThuTuToHIS(pMaBenhNhan, pLoaiCLS, pSoThuTu);
        }
        
        public System.Threading.Tasks.Task<bool> SendSoThuTuToHISAsync(string pMaBenhNhan, string pLoaiCLS, string pSoThuTu) {
            return base.Channel.SendSoThuTuToHISAsync(pMaBenhNhan, pLoaiCLS, pSoThuTu);
        }
        
        public string LayDanhSachDatHenTrongNgay() {
            return base.Channel.LayDanhSachDatHenTrongNgay();
        }
        
        public System.Threading.Tasks.Task<string> LayDanhSachDatHenTrongNgayAsync() {
            return base.Channel.LayDanhSachDatHenTrongNgayAsync();
        }
        
        public string LayThongTinDatHen_ByMaBenhNhan(string pMaBenhNhan) {
            return base.Channel.LayThongTinDatHen_ByMaBenhNhan(pMaBenhNhan);
        }
        
        public System.Threading.Tasks.Task<string> LayThongTinDatHen_ByMaBenhNhanAsync(string pMaBenhNhan) {
            return base.Channel.LayThongTinDatHen_ByMaBenhNhanAsync(pMaBenhNhan);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QMS_BenhVien.HISReference.Valid_TiepNhanResponse QMS_BenhVien.HISReference.IHISService.Valid_TiepNhan(QMS_BenhVien.HISReference.Valid_TiepNhanRequest request) {
            return base.Channel.Valid_TiepNhan(request);
        }
        
        public bool Valid_TiepNhan(string pMaBenhNhan, ref string pMessage) {
            QMS_BenhVien.HISReference.Valid_TiepNhanRequest inValue = new QMS_BenhVien.HISReference.Valid_TiepNhanRequest();
            inValue.pMaBenhNhan = pMaBenhNhan;
            inValue.pMessage = pMessage;
            QMS_BenhVien.HISReference.Valid_TiepNhanResponse retVal = ((QMS_BenhVien.HISReference.IHISService)(this)).Valid_TiepNhan(inValue);
            pMessage = retVal.pMessage;
            return retVal.Valid_TiepNhanResult;
        }
        
        public System.Threading.Tasks.Task<QMS_BenhVien.HISReference.Valid_TiepNhanResponse> Valid_TiepNhanAsync(QMS_BenhVien.HISReference.Valid_TiepNhanRequest request) {
            return base.Channel.Valid_TiepNhanAsync(request);
        }
    }
}
